# Generated by Django 4.2.5 on 2024-04-11 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_followerscount_likepost_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
